# Generated by Django 6.1.2 on 2026-10-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_asignee_email_task_assignee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_hours_before', models.PositiveIntegerField(default=24, help_text='Send deadline notification this many hours before the deadline.')),
            ],
            options={
                'verbose_name': 'Scheduler Configuration',
            },
        ),
    ]
