# Generated by Django 6.1.2 on 2026-10-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_schedulerconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline_timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
